### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function set_magic_quotes_runtime()

### ISSUE THREAD

**Issue by itaymbere** [intelliants/elitius#5]
( ! ) Fatal error: Uncaught Error: Call to undefined function set_magic_quotes_runtime() in /var/www/elitius/install/index.php on line 25
( ! ) Error: Call to undefined function set_magic_quotes_runtime() in /var/www/elitius/afiliados/install/index.php on line 25

**Comment by vbezruchkin** [comment]
Hi,

The project is dead. Please stop using it.
We will archive the project today.

Thanks
